// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Message from "./Message.bs.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function App(props) {
  var match = React.useState(function () {
        return [];
      });
  var setMessages = match[1];
  var match$1 = React.useState(function () {
        return "";
      });
  var setValue = match$1[1];
  var value = match$1[0];
  var onClick = function (param) {
    var new_message = {
      user_name: "me",
      avatar: "pepita.jpg",
      message: value
    };
    Curry._1(setValue, (function (param) {
            return "";
          }));
    Curry._1(setMessages, (function (messages) {
            return messages.concat([new_message]);
          }));
    setTimeout((function (param) {
            Curry._1(setMessages, (function (messages) {
                    return messages.concat([{
                                  user_name: "janet",
                                  avatar: "janet.jpg",
                                  message: "Janet"
                                }]);
                  }));
          }), 400);
  };
  var handleInputChange = function (e) {
    var s = e.currentTarget.value;
    Curry._1(setValue, (function (param) {
            return s;
          }));
  };
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("div", {
                      children: JsxRuntime.jsx("span", {
                            children: "Janet Chat",
                            className: "text-white text-xl"
                          }),
                      className: "absolute bg-zinc-800 w-full h-20 flex items-center p-4  overflow-hidden top-0 left-0"
                    }),
                JsxRuntime.jsx("div", {
                      children: JsxRuntime.jsx("div", {
                            children: match[0].map(function (msg) {
                                  return JsxRuntime.jsx(Message.make, {
                                              message: msg
                                            });
                                }),
                            className: "flex flex-col"
                          }),
                      className: "absolute top-20 bottom-20 flex overflow-auto w-full flex-col-reverse bg-[#343541]"
                    }),
                JsxRuntime.jsx("div", {
                      children: JsxRuntime.jsxs("div", {
                            children: [
                              JsxRuntime.jsx("input", {
                                    className: "w-11/12 resize-none whitespace-nowrap bg-[#41414e] text-white focus:outline-none",
                                    cols: 70,
                                    placeholder: "Send a message...",
                                    value: value,
                                    onKeyDown: (function (e) {
                                        if (e.key === "Enter") {
                                          return onClick(undefined);
                                        }
                                        
                                      }),
                                    onChange: handleInputChange
                                  }),
                              JsxRuntime.jsx("div", {
                                    children: JsxRuntime.jsx("img", {
                                          src: "send.svg"
                                        }),
                                    className: "rounded-full h-8 w-8 focus:outline-none p-2 cursor-pointer",
                                    onClick: onClick
                                  })
                            ],
                            className: "flex justify-center p-1 w-9/12 h-10 rounded-lg border border-[#32323d] bg-[#41414e]"
                          }),
                      className: "absolute bottom-0 left-0 flex items-center justify-center h-20 bg-[#353740] w-full"
                    })
              ],
              className: "h-screen w-full"
            });
}

var make = App;

export {
  make ,
}
/* react Not a pure module */
