// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function Message(props) {
  var message = props.message;
  var is_janet = message.user_name === "janet";
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("div", {
                      children: JsxRuntime.jsx("img", {
                            alt: message.user_name,
                            src: message.avatar
                          }),
                      className: "w-10 h-10 overflow-hidden rounded-full"
                    }),
                JsxRuntime.jsx("div", {
                      children: message.message,
                      className: "text-[#d8e8e2] pt-2 texl-lg"
                    })
              ],
              className: "flex py-6 px-20 h-min w-full gap-2 " + (
                is_janet ? "bg-[#444755]" : "bg-[#343541]"
              ) + ""
            });
}

var make = Message;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
